spring.application.name=application
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
management.endpoints.web.exposure.include=*
management.endpoint.shutdown.enabled=false
management.endpoints.web.base-path=/admin/actuator
management.metrics.export.prometheus.enabled=true
spring.security.user.name=admin
spring.security.user.password=secret