CREATE TABLE universities (
    university_id  bigint primary key generated by default as identity,
    university_name VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL
);

CREATE TABLE users (
    user_id  bigint primary key generated by default as identity,
    user_name VARCHAR(255) NOT NULL,
    user_surname VARCHAR(255) NOT NULL,
    university_id BIGINT,
    FOREIGN KEY (university_id) REFERENCES universities(university_id)
);

CREATE TABLE books (
    book_id  bigint primary key generated by default as identity,
    author VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL
);

CREATE TABLE courses (
    course_id  bigint primary key generated by default as identity,
    course_name VARCHAR(255) NOT NULL
);

CREATE TABLE book_user (
    user_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, book_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (book_id) REFERENCES books(book_id)
);

CREATE TABLE course_user (
    user_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, course_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (course_id) REFERENCES courses(course_id)
);

INSERT INTO users (user_id, user_name, user_surname) VALUES (42, "Анатолий", "Корнилов");
